TaskSolution/Portal/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TaskSolution/Portal/Controllers/TaskController.cs
using System.Web.Mvc;
using BLL;
using BLL.Contracts;
using Model;
using Portal.Utilities;
using Portal.ViewModel;

namespace Portal.Controllers
{
    public class TaskController : Controller
    {
        private static readonly ITaskBll<Task> _TASKBLL = new TaskBll<Task>(); 
        
        public ActionResult GetAll()
        {
            var tasks = _TASKBLL.GetAll();
            if (tasks == null) return View();
            var tasksGetVms = tasks.ToTaskGetVMList();
            return View(tasksGetVms);
        }        
        
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskCVM model)
        {
            try
            {
                if (ModelState.IsValid == false) return View(model);
                _TASKBLL.AddTask(model.ToTask());
                return RedirectToAction("GetAll");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(string taskId)
        {
            if (string.IsNullOrWhiteSpace(taskId)) RedirectToAction("GetAll");
            var subTasks = _TASKBLL.GetSubTasks(taskId);
            if (subTasks == null) return View();
            var tasksGetVms = subTasks.ToTaskGetVMList();
            return View(tasksGetVms);            
        }

        public ActionResult CreateSubtask(string taskId)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSubtask(string taskId, TaskCVM model)
        {
            try
            {
                if (ModelState.IsValid == false) return View(model);
                _TASKBLL.AddSubTask(taskId, model.ToTask());
                return RedirectToAction("Details", new {taskId = taskId});
            }
            catch
            {
                return View();
            }
        }
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TaskSolution/Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TaskSolution/Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TaskSolution/Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">            
        <h2>@Html.ActionLink("Tasks", "GetAll", "Task")</h2>
    </div>    
</div>

TaskSolution/Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All tasks", "GetAll", "Task")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaskSolution/Portal/Views/Task/Create.cshtml
@model Portal.ViewModel.TaskCVM

@{
    ViewBag.Title = "Create";
}

<h2>Create task</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="body-content form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>   
            </div>            
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>           
        </div>            
        <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-sm-10", style = "width: 100%" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Severity, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Severity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Severity, "", new { @class = "text-danger" })
                    </div>
                </div> 
            </div>           
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Status, new { htmlAttributes = new { @class = "form-control"} })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br/>       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <span>
                    @Html.ActionLink("Cancel", "GetAll", null, new { @class = "btn btn-default" })                    
                </span>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskSolution/Portal/Views/Task/CreateSubtask.cshtml
@model Portal.ViewModel.TaskCVM

@{
    ViewBag.Title = "Create subtask";
}

<h2>Create sub task</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="body-content form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-sm-10", style = "width: 100%" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Severity, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Severity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Severity, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
                    <div>
                        @Html.EnumDropDownListFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <span>
                    @Html.ActionLink("Cancel", "Details", new { taskId = @Request.QueryString["taskId"] }, new { @class = "btn btn-default" })
                </span>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskSolution/Portal/Views/Task/Details.cshtml
@model IEnumerable<Portal.ViewModel.TaskGetVM>

@{
    ViewBag.Title = "Sub-Tasks" ;
}
<br />

<h2>Sub-Tasks</h2>
<br />
<br />

<p>
    @Html.ActionLink("Create New", "CreateSubtask", new {taskId = @Request.QueryString["taskId"]}, new { @class = "btn btn-primary" })
</p>
<br />
<br />

@{ Html.RenderPartial("_DetailsFilters");    }
<br />
<br />
@if (Model == null)
{
    <div>
        No sub-tasks were found.
    </div>

}
else
{
    <table class="table table-striped table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Severity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Status
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Severity
                </td>
                <td>
                    @item.Priority
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    <button class="btn btn-info">Edit</button> | 
                    @Html.ActionLink("Sub-Tasks", "Details", new { taskId = item.ID }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }

    </table>
}

TaskSolution/Portal/Views/Task/GetAll.cshtml
@model IEnumerable<Portal.ViewModel.TaskGetVM>

@{
    ViewBag.Title = "all tasks";
}
<br />

<h2>All tasks</h2>
<br/>
<br />

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<br />
<br />

@{ Html.RenderPartial("_Filters");    }
<br/>
<br/>
@if (Model == null)
{
    <div>
        No tasks were found.
    </div>

}
else
{
    <table class="table table-striped table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Severity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Status
                </td>
                <td>
                   @item.Title
                </td>
                <td>
                    @item.Severity
                </td>
                <td>
                    @item.Priority
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    <button class="btn btn-info">Edit</button> |
                    @Html.ActionLink("Sub-Tasks", "Details", new { taskId = item.ID }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }

    </table>
}

TaskSolution/Portal/Views/Task/_DetailsFilters.cshtml
<div class="row">
    <table class="table-bordered"> 
        <tr>
            <td>Sort by</td>
            <td colspan="2">@Html.TextBox("t_sortBy")</td>
        </tr>     
    </table>    
</div>

TaskSolution/Portal/Views/Task/_Filters.cshtml
<div class="row">
    <table class="table-bordered">
        <tr>
            <td>Title</td>
            <td colspan="2">@Html.TextBox("t_title")</td>
        </tr>
        <tr>
            <td>Description</td>
            <td colspan="2">@Html.TextBox("t_description")</td>
        </tr>
        <tr>
            <td>Status</td>
            <td colspan="2">@Html.TextBox("t_status")</td>
        </tr>
        <tr>
            <td>Date</td>
            <td>@Html.TextBox("t_date")</td>
            <td>@Html.TextBox("t_date")</td>
        </tr>   
        <tr>
            <td>Sort by</td>
            <td colspan="2">@Html.TextBox("t_sortBy")</td>
        </tr>     
    </table>    
</div>